site_name: mappView custom widgets
use_directory_urls: false

extra_css: [extra.css]
    
nav:
  - Start: index.md
  - Installation: installation.md
  - DropDownBox: widgets_drop_down_box.md
  - NumericInput: widgets_numeric_input.md
  - Screenshot: widgets_screenshot.md
  - Transfer: widgets_transfer.md
  - ToggleSwitch: widgets_toggle_switch.md
  - ListBox: widgets_list_box.md
  - Revision: revision.md

theme:
    name: material
    logo: images/bur.png

    palette:
      scheme: default
      primary: orange
      accent: orange

    features: toc.integrate

plugins:
  - search
      
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/br-automation-com/mappView-CustomWidgets
repo_name: GitHub Repo

